export SERVICE_PORT=3004 
export DB_SERVER=msapiuat-rds.z5.com 
export DB_PORT=5432 
export DB_USER=weyyak_aurora 
export DB_PASSWORD=M5Ltay9sDY93khvmcpNE 
export DB_DATABASE=wyk_frontend_config 
export CDB_DATABASE=wyk_content 
export FDB_DATABASE=wk_frontend 
export USER_DB_DATABASE=wk_user_management 
export DEFAULT_PAGE_SIZE=50 
export CMS=https://sytz9mbysb.execute-api.ap-south-1.amazonaws.com/weyyak-fo-ms-api-uat/v1/ 
export UM=https://sytz9mbysb.execute-api.ap-south-1.amazonaws.com/weyyak-fo-ms-api-uat/v1/ 
export IMAGES=https://contents-uat.weyyak.z5.com/ 
export GEO_LOCATION=https://geo.weyyak1.z5.com 
export VIDEO_API=https://api-weyyak.akamaized.net/get_info/ 
export AD_TAG_URL=https://s3.ap-south-1.amazonaws.com/z5xml/mobile_apps_ads_ios.xml 
export BASE_URL=https://sytz9mbysb.execute-api.ap-south-1.amazonaws.com/weyyak-fo-ms-api-uat/v1/ 
export S3_BUCKET=z5content-uat 
export S3_REGION=ap-south-1 
export S3_ID=AKIAYOGUWMUMGAQLMW3U 
export S3_SECRET=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 
export HOME_PAGE_FOR_TV=https://msapifo-uat.weyyak.z5.com/v1/ 
export REDIS_RDS=43.205.196.77:6379 
export REDIS_CACHE_URL=https://msapiuat-events.z5.com/cache 
export DOTNET_URL=https://uat-api.weyyak.z5.com/v1/ar/oauth2/tokendata?access_token=
go run *.go