info:
  contact: {}
paths:
  /v1/contents/onetier/{content_key}:
    get:
      consumes:
      - application/json
      description: Get One Tier Content Details Based on Content ID
      parameters:
      - description: Content Key
        in: path
        name: content_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: object
            type: array
      security:
      - Authorization: []
      summary: Get One Tier Content Details Based on Content ID
      tags:
      - OneTier
swagger: "2.0"
