// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/contents/multitier": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "Get All Multi Tier Content Details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MultiTier"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Zero-based index of the first requested item.",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Maximum number of collection items to return for a single request.",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Country code of the user.",
                        "name": "country",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/content.AllMultiTier"
                        }
                    },
                    "404": {
                        "description": "The object was not found."
                    },
                    "500": {
                        "description": "Internal server error.",
                        "schema": {
                            "$ref": "#/definitions/content.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/contents/multitier/{contentId}": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "Get Multi Tier Content Details Based on Content ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MultiTier"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Content ID",
                        "name": "contentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Country code of the user.",
                        "name": "country",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/content.MultiTierContent"
                            }
                        }
                    },
                    "404": {
                        "description": "The object was not found."
                    },
                    "500": {
                        "description": "Internal server error.",
                        "schema": {
                            "$ref": "#/definitions/content.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/contents/onetier": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "Get All One Tier Contents Details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OneTier"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Zero-based index of the first requested item.",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Maximum number of collection items to return for a single request.",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Country code of the user.",
                        "name": "country",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/content.Response"
                        }
                    },
                    "404": {
                        "description": "The object was not found."
                    },
                    "500": {
                        "description": "Internal server error.",
                        "schema": {
                            "$ref": "#/definitions/content.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/contents/onetier/{contentId}": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "Get One Tier Content Details Based on Content ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OneTier"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Content Id.",
                        "name": "contentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Country code of the user.",
                        "name": "country",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/content.OnetierContent"
                            }
                        }
                    },
                    "404": {
                        "description": "The object was not found."
                    },
                    "500": {
                        "description": "Internal server error.",
                        "schema": {
                            "$ref": "#/definitions/content.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/episode/{contentId}": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "Get Episode Details By Episode Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MultiTier"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Content Id",
                        "name": "contentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Country code of the user",
                        "name": "country",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/content.EpisodeResult"
                        }
                    },
                    "404": {
                        "description": "The object was not found."
                    },
                    "500": {
                        "description": "Internal server error.",
                        "schema": {
                            "$ref": "#/definitions/content.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/get_info/{videoId}": {
            "get": {
                "description": "Get all menu list details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Video"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "video Id.",
                        "name": "videoId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Country code of the user.",
                        "name": "country",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/content.VideoDurationInfo"
                        }
                    },
                    "404": {
                        "description": "The object was not found."
                    },
                    "500": {
                        "description": "Internal server error.",
                        "schema": {
                            "$ref": "#/definitions/content.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/get_menu": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "Get All menu list details by platform ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device Name",
                        "name": "device",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/content.MenuDetails"
                        }
                    },
                    "404": {
                        "description": "The object was not found."
                    },
                    "500": {
                        "description": "Internal server error.",
                        "schema": {
                            "$ref": "#/definitions/content.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/get_page/{pageId}": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "Get All menu list details by platform ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Page Id",
                        "name": "pageId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Country code of the user.",
                        "name": "country",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/content.PageDetails"
                        }
                    },
                    "404": {
                        "description": "The object was not found."
                    },
                    "500": {
                        "description": "Internal server error.",
                        "schema": {
                            "$ref": "#/definitions/content.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/oauth2/token": {
            "post": {
                "description": "User login with generate token",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "User login with generate token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter Username",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Enter Password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success"
                    },
                    "400": {
                        "description": "Bad Request."
                    },
                    "401": {
                        "description": "Authorization has been denied for this request."
                    }
                }
            }
        }
    },
    "/v1/contents/deleted": {
        "get": {
            "security": [
                {
                    "Authorization": []
                }
            ],
            "description": "Get All Deleted Content Details",
            "consumes": [
                "application/json"
            ],
            "produces": [
                "application/json"
            ],
            "tags": [
                "Content Updates"
            ],
            "parameters": [
                {
                    "type": "string",
                    "format": "date",
                    "example": "2000-01-01",
                    "description": "Date from which deleted data to be fetched.",
                    "name": "from",
                    "in": "query"
                },
                {
                    "type": "string",
                    "format": "date",
                    "example": "2000-01-01",
                    "description": "Date to which deleted data to be fetched.",
                    "name": "to",
                    "in": "query"
                }
            ],
            "responses": {
                "200": {
                    "description": "OK",
                    "schema": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "404": {
                    "description": "The object was not found."
                },
                "500": {
                    "description": "Internal server error.",
                    "schema": {
                        "$ref": "#/definitions/content.ErrorResponse"
                    }
                }
            }
        }
    },
    "/v1/contents/modified": {
        "get": {
            "security": [
                {
                    "Authorization": []
                }
            ],
            "description": "Get All Modified Content Details",
            "consumes": [
                "application/json"
            ],
            "produces": [
                "application/json"
            ],
            "tags": [
                "Content Updates"
            ],
            "parameters": [
                {
                    "type": "string",
                    "format": "date",
                    "example": "2000-01-01",
                    "description": "Date from which modified data to be fetched.",
                    "name": "from",
                    "in": "query"
                },
                {
                    "type": "string",
                    "format": "date",
                    "example": "2000-01-01",
                    "description": "Date to which modified data to be fetched.",
                    "name": "to",
                    "in": "query"
                }
            ],
            "responses": {
                "200": {
                    "description": "OK",
                    "schema": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "404": {
                    "description": "The object was not found."
                },
                "500": {
                    "description": "Internal server error.",
                    "schema": {
                        "$ref": "#/definitions/content.ErrorResponse"
                    }
                }
            }
        }
    }
    "definitions": {
        "content.AboutTheContent": {
            "type": "object",
            "properties": {
                "acquisitionDepartment": {
                    "type": "string"
                },
                "ageGroups": {
                    "type": "integer"
                },
                "arabicSynopsis": {
                    "type": "string"
                },
                "englishSynopsis": {
                    "type": "string"
                },
                "originalLanguage": {
                    "type": "string"
                },
                "productionCountries": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "productionHouse": {
                    "type": "string"
                },
                "productionYear": {
                    "type": "integer"
                },
                "supplier": {
                    "type": "string"
                }
            }
        },
        "content.AllContentSeasons": {
            "type": "object",
            "properties": {
                "aboutTheContent": {
                    "$ref": "#/definitions/content.AboutTheContent"
                },
                "cast": {
                    "$ref": "#/definitions/content.Cast"
                },
                "contentId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "description": "season ID",
                    "type": "string"
                },
                "modifiedAt": {
                    "type": "string"
                },
                "music": {
                    "$ref": "#/definitions/content.Music"
                },
                "nonTextualData": {
                    "$ref": "#/definitions/content.ContentNonTextualData"
                },
                "primaryInfo": {
                    "$ref": "#/definitions/content.SeasonPrimaryInfo"
                },
                "rights": {
                    "$ref": "#/definitions/content.Rights"
                },
                "seasonKey": {
                    "type": "integer"
                },
                "seasonNumber": {
                    "type": "integer"
                },
                "tagInfo": {
                    "$ref": "#/definitions/content.TagInfo"
                },
                "translation": {
                    "$ref": "#/definitions/content.Translation"
                }
            }
        },
        "content.AllMultiTier": {
            "type": "object",
            "properties": {
                "contentGenres": {
                    "type": "array",
                    "items": {}
                },
                "contentKey": {
                    "type": "string"
                },
                "contentSeasons": {
                    "$ref": "#/definitions/content.AllContentSeasons"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "modifiedAt": {
                    "type": "string"
                },
                "primaryInfo": {
                    "$ref": "#/definitions/content.ContentPrimaryInfo"
                },
                "seoDetails": {
                    "$ref": "#/definitions/content.SeoDetails"
                }
            }
        },
        "content.AllOnetierContent": {
            "type": "object",
            "properties": {
                "aboutTheContent": {
                    "$ref": "#/definitions/content.AboutTheContent"
                },
                "cast": {
                    "$ref": "#/definitions/content.Cast"
                },
                "contentGenres": {
                    "type": "array",
                    "items": {}
                },
                "contentKey": {
                    "type": "integer"
                },
                "contentVariances": {
                    "type": "array",
                    "items": {}
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "modifiedAt": {
                    "description": "InsertedAt       time.Time       ` + "`" + `json:\"insertedAt,omitempty\"` + "`" + `",
                    "type": "string"
                },
                "music": {
                    "$ref": "#/definitions/content.Music"
                },
                "nonTextualData": {
                    "$ref": "#/definitions/content.NonTextualData"
                },
                "primaryInfo": {
                    "$ref": "#/definitions/content.PrimaryInfo"
                },
                "seoDetails": {
                    "$ref": "#/definitions/content.SeoDetails"
                },
                "tagInfo": {
                    "$ref": "#/definitions/content.TagInfo"
                }
            }
        },
        "content.Cast": {
            "type": "object",
            "properties": {
                "actorArabic": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "actorEnglish": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "actorIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "castId": {
                    "type": "string"
                },
                "directorArabic": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "directorEnglish": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "directorIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mainActorArabic": {
                    "type": "string"
                },
                "mainActorEnglish": {
                    "type": "string"
                },
                "mainActorId": {
                    "type": "string"
                },
                "mainActressArabic": {
                    "type": "string"
                },
                "mainActressEnglish": {
                    "type": "string"
                },
                "mainActressId": {
                    "type": "string"
                },
                "writerArabic": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "writerEnglish": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "writerIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "content.ContentImageryDetails": {
            "type": "object",
            "properties": {
                "backdrop": {
                    "type": "string"
                },
                "featured_img": {
                    "type": "string"
                },
                "mobile_img": {
                    "type": "string"
                },
                "overlayPoster": {
                    "type": "string"
                },
                "thumbnail": {
                    "type": "string"
                }
            }
        },
        "content.ContentNonTextualData": {
            "type": "object",
            "properties": {
                "detailsBackground": {
                    "type": "string"
                },
                "mobileDetailsBackground": {
                    "type": "string"
                },
                "overlayPosterImage": {
                    "type": "string"
                },
                "posterImage": {
                    "type": "string"
                }
            }
        },
        "content.ContentPrimaryInfo": {
            "type": "object",
            "properties": {
                "alternativeTitle": {
                    "type": "string"
                },
                "arabicTitle": {
                    "type": "string"
                },
                "contentType": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "originalTitle": {
                    "type": "string"
                },
                "transliteratedTitle": {
                    "type": "string"
                }
            }
        },
        "content.ContentSeasons": {
            "type": "object",
            "properties": {
                "aboutTheContent": {
                    "$ref": "#/definitions/content.AboutTheContent"
                },
                "cast": {
                    "$ref": "#/definitions/content.Cast"
                },
                "contentId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "digitalRightsRegions": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "episodes": {
                    "type": "array",
                    "items": {}
                },
                "id": {
                    "description": "season ID",
                    "type": "string"
                },
                "modifiedAt": {
                    "type": "string"
                },
                "music": {
                    "$ref": "#/definitions/content.Music"
                },
                "nonTextualData": {
                    "$ref": "#/definitions/content.ContentNonTextualData"
                },
                "primaryInfo": {
                    "$ref": "#/definitions/content.SeasonPrimaryInfo"
                },
                "seasonGeneres": {
                    "type": "array",
                    "items": {}
                },
                "seasonKey": {
                    "type": "integer"
                },
                "seasonNumber": {
                    "type": "integer"
                },
                "tagInfo": {
                    "$ref": "#/definitions/content.TagInfo"
                },
                "translation": {
                    "$ref": "#/definitions/content.Translation"
                }
            }
        },
        "content.EpisodeResult": {
            "type": "object",
            "properties": {
                "cast": {
                    "$ref": "#/definitions/content.Cast"
                },
                "contentId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "digitalRightsRegions": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "episodeKey": {
                    "type": "integer"
                },
                "episodeNumber": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "length": {
                    "type": "integer"
                },
                "modifiedAt": {
                    "type": "string"
                },
                "music": {
                    "$ref": "#/definitions/content.Music"
                },
                "nonTextualData": {
                    "$ref": "#/definitions/content.NowTextualDataEpisode"
                },
                "primaryInfo": {
                    "$ref": "#/definitions/content.PrimaryInfo"
                },
                "seasonId": {
                    "type": "string"
                },
                "seoDetails": {
                    "$ref": "#/definitions/content.SeoDetails"
                },
                "synopsisArabic": {
                    "type": "string"
                },
                "synopsisEnglish": {
                    "type": "string"
                },
                "tagInfo": {
                    "$ref": "#/definitions/content.TagInfo"
                },
                "translation": {
                    "$ref": "#/definitions/content.Translation"
                },
                "videoContentUrl": {
                    "type": "string"
                }
            }
        },
        "content.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "invalid": {
                    "type": "object",
                    "properties": {
                        "additionalProp1": {
                            "type": "object",
                            "properties": {
                                "code": {
                                    "type": "string"
                                },
                                "description": {
                                    "type": "string"
                                }
                            }
                        },
                        "additionalProp2": {
                            "type": "object",
                            "properties": {
                                "code": {
                                    "type": "string"
                                },
                                "description": {
                                    "type": "string"
                                }
                            }
                        },
                        "additionalProp3": {
                            "type": "object",
                            "properties": {
                                "code": {
                                    "type": "string"
                                },
                                "description": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "content.FeaturedDetails": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "playlists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/content.FeaturedPlaylists"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "content.FeaturedPlaylists": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/content.PlaylistContent"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "playlist_type": {
                    "type": "string"
                }
            }
        },
        "content.MenuData": {
            "type": "object",
            "properties": {
                "featured": {
                    "$ref": "#/definitions/content.FeaturedDetails"
                },
                "friendly_url_arabic": {
                    "type": "string"
                },
                "friendly_url_english": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "playlists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/content.MenuPlaylists"
                    }
                },
                "seo_description": {
                    "type": "string"
                },
                "title_arabic": {
                    "type": "string"
                },
                "title_english": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "content.MenuDetails": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/content.MenuData"
                    }
                },
                "from": {
                    "type": "integer"
                },
                "last_page": {
                    "type": "integer"
                },
                "next_page_url": {
                    "type": "string"
                },
                "per_page": {
                    "type": "integer"
                },
                "prev_page_url": {
                    "type": "string"
                },
                "to": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "content.MenuPlaylists": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/content.PlaylistContent"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "title_arabic": {
                    "type": "string"
                },
                "title_english": {
                    "type": "string"
                }
            }
        },
        "content.MultiTierContent": {
            "type": "object",
            "properties": {
                "contentGenres": {
                    "type": "array",
                    "items": {}
                },
                "contentKey": {
                    "type": "string"
                },
                "contentSeasons": {
                    "$ref": "#/definitions/content.ContentSeasons"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "description": "content ID",
                    "type": "string"
                },
                "modifiedAt": {
                    "type": "string"
                },
                "primaryInfo": {
                    "$ref": "#/definitions/content.ContentPrimaryInfo"
                },
                "seoDetails": {
                    "$ref": "#/definitions/content.SeoDetails"
                }
            }
        },
        "content.Music": {
            "type": "object",
            "properties": {
                "musicComposerIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "musicComposersArabic": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "musicComposersEnglish": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "musicId": {
                    "type": "string"
                },
                "singerIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "singersArabic": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "singersEnglish": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "songWriterIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "songWritersArabic": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "songWritersEnglish": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "content.NonTextualData": {
            "type": "object",
            "properties": {
                "detailsBackground": {
                    "type": "string"
                },
                "dubbingScript": {
                    "type": "string"
                },
                "mobileDetailsBackground": {
                    "type": "string"
                },
                "overlayPosterImage": {
                    "type": "string"
                },
                "posterImage": {
                    "type": "string"
                },
                "subtitlingScript": {
                    "type": "string"
                }
            }
        },
        "content.NowTextualDataEpisode": {
            "type": "object",
            "properties": {
                "detailsBackground": {
                    "type": "string"
                },
                "dubbingScript": {
                    "type": "string"
                },
                "mobileDetailsBackground": {
                    "type": "string"
                },
                "overlayPosterImage": {
                    "type": "string"
                },
                "posterImage": {
                    "type": "string"
                },
                "subtitlingScript": {
                    "type": "string"
                }
            }
        },
        "content.OnetierContent": {
            "type": "object",
            "properties": {
                "aboutTheContent": {
                    "$ref": "#/definitions/content.AboutTheContent"
                },
                "cast": {
                    "$ref": "#/definitions/content.Cast"
                },
                "contentGenres": {
                    "type": "array",
                    "items": {}
                },
                "contentKey": {
                    "type": "integer"
                },
                "contentVariances": {
                    "type": "array",
                    "items": {}
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "modifiedAt": {
                    "description": "InsertedAt       time.Time       ` + "`" + `json:\"insertedAt,omitempty\"` + "`" + `",
                    "type": "string"
                },
                "music": {
                    "$ref": "#/definitions/content.Music"
                },
                "nonTextualData": {
                    "$ref": "#/definitions/content.NonTextualData"
                },
                "primaryInfo": {
                    "$ref": "#/definitions/content.PrimaryInfo"
                },
                "seoDetails": {
                    "$ref": "#/definitions/content.SeoDetails"
                },
                "tagInfo": {
                    "$ref": "#/definitions/content.TagInfo"
                }
            }
        },
        "content.PageDetails": {
            "type": "object",
            "properties": {
                "arabic_meta_description": {
                    "type": "string"
                },
                "arabic_page_friendly_url": {
                    "type": "string"
                },
                "arabic_title": {
                    "type": "string"
                },
                "english_meta_description": {
                    "type": "string"
                },
                "english_page_friendly_url": {
                    "type": "string"
                },
                "english_title": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "page_key": {
                    "type": "integer"
                },
                "page_type": {
                    "type": "integer"
                }
            }
        },
        "content.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "content.PlaylistContent": {
            "type": "object",
            "properties": {
                "age_rating": {
                    "type": "string"
                },
                "content_id": {
                    "type": "string"
                },
                "content_key": {
                    "type": "integer"
                },
                "content_type": {
                    "type": "string"
                },
                "friendly_url": {
                    "type": "string"
                },
                "imagery": {
                    "$ref": "#/definitions/content.ContentImageryDetails"
                },
                "inserted_at": {
                    "type": "string"
                },
                "length": {
                    "type": "integer"
                },
                "modified_at": {
                    "type": "string"
                },
                "seo_description_arabic": {
                    "type": "string"
                },
                "seo_description_english": {
                    "type": "string"
                },
                "seo_title": {
                    "type": "string"
                },
                "seo_title_arabic": {
                    "type": "string"
                },
                "seo_title_english": {
                    "type": "string"
                },
                "synopsis_arabic": {
                    "type": "string"
                },
                "synopsis_english": {
                    "type": "string"
                },
                "title_arabic": {
                    "type": "string"
                },
                "title_english": {
                    "type": "string"
                },
                "video_id": {
                    "type": "string"
                }
            }
        },
        "content.PrimaryInfo": {
            "type": "object",
            "properties": {
                "alternativeTitle": {
                    "type": "string"
                },
                "arabicTitle": {
                    "type": "string"
                },
                "contentTier": {
                    "type": "integer"
                },
                "contentType": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "originalTitle": {
                    "type": "string"
                },
                "seasonNumber": {
                    "type": "integer"
                },
                "synopsisArabic": {
                    "type": "string"
                },
                "synopsisEnglish": {
                    "type": "string"
                },
                "transliteratedTitle": {
                    "type": "string"
                },
                "videoContentId": {
                    "type": "string"
                }
            }
        },
        "content.Response": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/content.AllOnetierContent"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/content.Pagination"
                }
            }
        },
        "content.Rights": {
            "type": "object",
            "properties": {
                "digitalRightsRegion": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "content.SeasonPrimaryInfo": {
            "type": "object",
            "properties": {
                "alternativeTitle": {
                    "type": "string"
                },
                "arabicTitle": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "originalTitle": {
                    "type": "string"
                },
                "seasonNumber": {
                    "type": "integer"
                },
                "transliteratedTitle": {
                    "type": "string"
                }
            }
        },
        "content.SeoDetails": {
            "type": "object",
            "properties": {
                "arabicMetaDescription": {
                    "type": "string"
                },
                "arabicMetaTitle": {
                    "type": "string"
                },
                "englishMetaDescription": {
                    "type": "string"
                },
                "englishMetaTitle": {
                    "type": "string"
                }
            }
        },
        "content.TagInfo": {
            "type": "object",
            "properties": {
                "tag": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "content.Translation": {
            "type": "object",
            "properties": {
                "dubbingDialectId": {
                    "type": "integer"
                },
                "dubbingLanguage": {
                    "type": "string"
                },
                "languageType": {
                    "type": "string"
                },
                "subtitlingLanguage": {
                    "type": "string"
                }
            }
        },
        "content.VideoDurationInfo": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "integer"
                },
                "thumbnails": {
                    "type": "array",
                    "items": {}
                },
                "url_trickplay": {
                    "type": "string"
                },
                "url_video": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Authorization": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
