export SERVICE_PORT=3000 
export DB_SERVER=msapiqa-rds.z5.com 
export DB_SERVER_READER=msapiqa-rds-ro.z5.com 
export DB_PORT=5432 
export DB_USER=weyyak_aurora 
export DB_PASSWORD=M5Ltay9sDY93khvmcpNE 
export DB_DATABASE=wk_user_management 
export CONTENT_DB_DATABASE=wyk_content 
export FRONTEND_DB_DATABASE=wyk_frontend_config 
export TEMPLATE_URL=/templates/ 
export EMAILIMAGEBASEURL=https://s3.ap-south-1.amazonaws.com/mailtemp/ 
export EMAILHEADIMAGEFILENAME=logo.png 
export EMAILCONTENTIMAGEFILENAME=devices.png 
export REDIRECTION_URL=https://wyk2qa.weyyak.com/ 
export ADMIN_MAIL=viveksrujan.kothapalli@engro.io 
export DEFAULT_PAGE_SIZE=20 
export AWS_REGION=ap-south-1 
export ACCESS_SECRET=AKIAYOGUWMUMEEQD6CPW 
export REFRESH_SECRET=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 
export PASSWORDCHANGEURL=https://wyk2boqa.weyyak.com/password? 
export ReCAPTCHA_SECRET=6LdNV9siAAAAAAIJ9j7sBr6oNgstd7Tx_qLHwQ9x
export BASE_URL=https://wyk2qa.weyyak.com 
export EGYPTBASE_URL=https://qa-weyyak1.z5.com 
export SUBSCRIPTION_URL=https://zpapi.wyk.z5.com/orders/ 
export USER_DELETE_URL=https://zpapi.wyk.z5.com/payment/registration/delete?id= 
export SES_REGION=ap-south-1 
export SES_ID=AKIAYOGUWMUMK2O4DT6B 
export SES_SECRET=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 
export DOTNET_URL=https://uat-api.weyyak.z5.com/v1/ar/oauth2/tokendata?access_token= 

go run *.go