definitions:
  competition.CompetitionUsers:
    properties:
      Alpha2code:
        type: string
      adultConsent:
        type: boolean
      ageRating:
        type: string
      arabicFullName:
        type: string
      countryOfResidence:
        type: integer
      email:
        type: string
      englishFullName:
        type: string
      gender:
        type: string
      mobile:
        type: string
      nationality:
        type: integer
      travelConsent:
        type: boolean
    required:
    - Alpha2code
    - adultConsent
    - ageRating
    - countryOfResidence
    - email
    - gender
    - mobile
    - nationality
    - travelConsent
    type: object
info:
  contact: {}
paths:
  /api/v1/users:
    post:
      consumes:
      - application/json
      description: Create competition user details
      parameters:
      - description: Raw JSON string
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/competition.CompetitionUsers'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      security:
      - Authorization: []
      summary: Create competition user details
      tags:
      - Competition Users
swagger: "2.0"
