// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/users": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "Create competition user details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Competition Users"
                ],
                "summary": "Create competition user details",
                "parameters": [
                    {
                        "description": "Raw JSON string",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/competition.CompetitionUsers"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "competition.CompetitionUsers": {
            "type": "object",
            "required": [
                "Alpha2code",
                "adultConsent",
                "ageRating",
                "countryOfResidence",
                "email",
                "gender",
                "mobile",
                "nationality",
                "travelConsent"
            ],
            "properties": {
                "Alpha2code": {
                    "type": "string"
                },
                "adultConsent": {
                    "type": "boolean"
                },
                "ageRating": {
                    "type": "string"
                },
                "arabicFullName": {
                    "type": "string"
                },
                "countryOfResidence": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "englishFullName": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                },
                "nationality": {
                    "type": "integer"
                },
                "travelConsent": {
                    "type": "boolean"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
